Repository Team-B1ND/dui-android, pull requests merged in 2023-02, with the labels that each got.

#32 DUI Preview App : Typo 페이지 개발 by kdh1123 Pull Request
  app/src/main/java/kr/hs/dgsw/smartschool/dui/root/MainActivity.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/MainScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TypoScreen.kt
Labels: FEATURE ⚡️

#33 DUI 코어 컴포넌트 : Bottom Sheet 개발하기
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/bottomsheet/BottomSheet.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/bottomsheet/BottomSheetDialog.kt
Labels: DESIGN 🎨, FEATURE ⚡️

#35 DUI Preview App : Icon 페이지 개발 by kdh1123 Pull Request
  app/src/main/java/kr/hs/dgsw/smartschool/dui/root/MainActivity.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/IconScreen.kt
Labels: FEATURE ⚡️

#37 DUI 코어 컴포넌트 : Calendar 개발하기
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/button/Button.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/button/DodamButton.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/calendar/Calendar.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/calendar/CalendarUtils.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/calendar/DodamBasicCalendarCategory.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/calendar/dialog/CalendarDialog.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/calendar/schedule/Schedule.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/calendar/schedule/ScheduleItem.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/prompt/Prompt.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/theme/DodamIcon.kt
  dodam-components/src/main/res/drawable/ic_calendar.xml
Labels: DESIGN 🎨, FEATURE ⚡️

#44 DUI 코어컴포넌트 : AppBar 개발
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/appbar/DodamAppBar.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/theme/DodamIcon.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/utlis/DodamDimen.kt
  dodam-components/src/main/res/drawable/ic_back_arrow.xml
Labels: DESIGN 🎨, FEATURE ⚡️

#45 DUI 코어컴포넌트 : CheckBox 개발
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/checkbox/DodamCheckBox.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/theme/DodamIcon.kt
  dodam-components/src/main/res/drawable/ic_check.xml
Labels: DESIGN 🎨, FEATURE ⚡️

#58 DUI 코어컴포넌트 : SelectArea 개발
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/input/SelectArea.kt
Labels: DESIGN 🎨, FEATURE ⚡️

#59 DUI Preview App : Button & Shape 페이지 개발 by kdh1123 Pull Request
  app/src/main/java/kr/hs/dgsw/smartschool/dui/DataSet.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/root/MainActivity.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ButtonScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/IconScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ShapeScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TypoScreen.kt
Labels: FEATURE ⚡️

#57 DUI 코어컴포넌트 : Switch 개발
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/button/Button.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/toggle/DodamSwitch.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/utlis/AnimationUtils.kt
Labels: DESIGN 🎨, FEATURE ⚡️

#61 DUI Preview App : Input & Tab 페이지 개발 by kdh1123 Pull Request
  app/src/main/java/kr/hs/dgsw/smartschool/dui/DataSet.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/root/MainActivity.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/AppBarScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/AvartarScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/BannerScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/BottomSheetScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ButtonScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CalenderScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CheckBoxScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ColorScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/IconScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/InputScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/MainScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/SelectScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ShapeScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/SwitchScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TabScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TypoScreen.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/input/InputArea.kt
Labels: FEATURE ⚡️

#63 DUI Preview App : avatar 페이지 만들기
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/AvartarScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ColorScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TypoScreen.kt
  app/src/main/res/drawable/img_dummy.jpeg
Labels: FEATURE ⚡️

#66 DUI 전체적인 점검
  app/src/main/java/kr/hs/dgsw/smartschool/dui/root/MainActivity.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ButtonScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CardScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/InputScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TabScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TypoScreen.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/Divider.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/Surface.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/avatar/Avatar.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/badge/DodamBadge.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/badge/DodamBadgeBox.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/button/Button.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/button/DodamButton.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/indicator/DodamPagerIndicator.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/input/DodamInput.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/input/DodamSelect.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/input/area/DodamInputArea.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/input/area/DodamSelectArea.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/toggle/DodamCheckBox.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/toggle/DodamSwitch.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/organization/bottomsheet/DodamBottomSheet.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/organization/bottomsheet/DodamBottomSheetDialog.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/organization/calendar/Calendar.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/organization/calendar/dialog/DodamCalendarDialog.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/organization/calendar/schedule/DodamScheduleItem.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/organization/card/Card.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/organization/card/DodamCard.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/organization/prompt/DodamPrompt.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/set/appbar/DodamAppBar.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/set/banner/DodamBanner.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/set/navtab/DodamNavBar.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/set/navtab/DodamNavTab.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/set/tab/DodamTab.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/set/tab/DodamTabs.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/foundation/Icon.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/foundation/Text.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/modifier/dodamClickable.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/theme/DodamTypography.kt
Labels: DESIGN 🎨, BUG 🐛

#67 DUI 1차 배포
  README.md
Labels: DOCUMENT 📄, RELEASE 🚀

#70 Add maven plugin and buildTypes
  buildSrc/src/main/java/Plugins.kt
  dodam-components/build.gradle.kts
Labels: BUG 🐛

#73 Jitpack 1.0.0 배포 오류 해결
  buildSrc/src/main/java/Plugins.kt
  dodam-components/build.gradle.kts
Labels: BUG 🐛

#71 DUI Preview App : Banner & Bottom Sheet 페이지 개발 by kdh1123 Pull Request
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/BannerScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/BottomSheetScreen.kt
Labels: FEATURE ⚡️

#74 Jitpack 1.0.1 에러 해결
  README.md
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/java/ProjectProperties.kt
  dodam-components/build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  jitpack.yml
Labels: BUG 🐛

#75 1.0.1 jitpack 오류 해결
  README.md
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/java/ProjectProperties.kt
  dodam-components/build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  jitpack.yml
Labels: BUG 🐛

#79 DUI Preiew App : calender 페이지 개발 by kdh1123 Pull Request
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CalenderScreen.kt
Labels: FEATURE ⚡️

#80 DUI Preview App : App Bar 페이지 개발 by kdh1123 Pull Request
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/AppBarScreen.kt
Labels: FEATURE ⚡️

#83 DUI Preview App : Input 페이지 추가 개발
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/InputScreen.kt
Labels: FEATURE ⚡️

#81 DUI Preview App : Toggle 페이지 개발 by kdh1123 Pull Request
  app/src/main/java/kr/hs/dgsw/smartschool/dui/DataSet.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/root/MainActivity.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CheckBoxScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/SwitchScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ToggleScreen.kt
Labels: FEATURE ⚡️

#84 DUI Preview App : Select 페이지 개발
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/SelectScreen.kt
Labels: FEATURE ⚡️

#87 가독성 떨어지는 딱딱한 readme를 예쁘게!
  README.md
  assets/dui_banner.png
Labels: DOCUMENT 📄

#86 가독성 떨어지는 딱딱한 readme를 예쁘게!
  README.md
  assets/dui_banner.png
Labels: DOCUMENT 📄

#88 Feature/60 preview check all
  app/src/main/java/kr/hs/dgsw/smartschool/dui/DataSet.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/AppBarScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/AvartarScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/BannerScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/BottomSheetScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ButtonScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CalenderScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CardScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ColorScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/IconScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/InputScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/MainScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/SelectScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ShapeScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TabScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ToggleScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TypoScreen.kt
  app/src/main/res/drawable/ic_app_bar_3d.png
  app/src/main/res/drawable/ic_avatar_3d.png
  app/src/main/res/drawable/ic_banner_3d.png
  app/src/main/res/drawable/ic_bottom_sheet_3d.png
  app/src/main/res/drawable/ic_button_3d.png
  app/src/main/res/drawable/ic_calendar_3d.png
  app/src/main/res/drawable/ic_card_3d.png
  app/src/main/res/drawable/ic_check_3d.png
  app/src/main/res/drawable/ic_input_3d.png
  app/src/main/res/drawable/ic_pencil_3d.png
  app/src/main/res/drawable/ic_select_3d.png
  app/src/main/res/drawable/ic_shape_3d.png
  app/src/main/res/drawable/ic_star_3d.png
  app/src/main/res/drawable/ic_tab_3d.png
Labels: FEATURE ⚡️

#91 버튼 text align 문제
  buildSrc/src/main/java/ProjectProperties.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/button/Button.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/button/DodamButton.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/input/DodamInput.kt
Labels: BUG 🐛

#90 버튼 text align 문제
  buildSrc/src/main/java/ProjectProperties.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/button/Button.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/button/DodamButton.kt
  dodam-components/src/main/java/kr/hs/dgsw/smartschool/components/component/basic/input/DodamInput.kt
Labels: BUG 🐛

#93 DUI Preview App : Release DUI preview 1.0.0
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/hs/dgsw/smartschool/dui/DataSet.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/root/MainActivity.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/AppBarScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/AvartarScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/BannerScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/BottomSheetScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ButtonScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CalenderScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CardScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/CheckBoxScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ColorScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/IconScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/InputScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/MainScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/SelectScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ShapeScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/SwitchScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TabScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/ToggleScreen.kt
  app/src/main/java/kr/hs/dgsw/smartschool/dui/screen/TypoScreen.kt
  app/src/main/res/drawable/ic_app_bar_3d.png
  app/src/main/res/drawable/ic_avatar_3d.png
  app/src/main/res/drawable/ic_banner_3d.png
  app/src/main/res/drawable/ic_bottom_sheet_3d.png
  app/src/main/res/drawable/ic_button_3d.png
  app/src/main/res/drawable/ic_calendar_3d.png
  app/src/main/res/drawable/ic_card_3d.png
  app/src/main/res/drawable/ic_check_3d.png
  app/src/main/res/drawable/ic_input_3d.png
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/drawable/ic_pencil_3d.png
  app/src/main/res/drawable/ic_select_3d.png
  app/src/main/res/drawable/ic_shape_3d.png
  app/src/main/res/drawable/ic_star_3d.png
  app/src/main/res/drawable/ic_tab_3d.png
Labels: RELEASE 🚀

#96 DUI Preview App : App Icon 적용 오류 수정
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/ic_logo-playstore.png
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/drawable/ic_logo_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_logo.png
  app/src/main/res/mipmap-hdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-hdpi/ic_logo_round.png
  app/src/main/res/mipmap-mdpi/ic_logo.png
  app/src/main/res/mipmap-mdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-mdpi/ic_logo_round.png
  app/src/main/res/mipmap-xhdpi/ic_logo.png
  app/src/main/res/mipmap-xhdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_logo_round.png
  app/src/main/res/mipmap-xxhdpi/ic_logo.png
  app/src/main/res/mipmap-xxhdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_logo_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo_round.png
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: BUG 🐛

#95 DUI Preview App : App Icon 적용 오류
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_logo.png
  buildSrc/src/main/java/ProjectProperties.kt
Labels: BUG 🐛

#97 DUI Preview App : app icon 적용 문제 수정
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/ic_logo-playstore.png
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/drawable/ic_logo_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_logo.png
  app/src/main/res/mipmap-hdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-hdpi/ic_logo_round.png
  app/src/main/res/mipmap-mdpi/ic_logo.png
  app/src/main/res/mipmap-mdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-mdpi/ic_logo_round.png
  app/src/main/res/mipmap-xhdpi/ic_logo.png
  app/src/main/res/mipmap-xhdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_logo_round.png
  app/src/main/res/mipmap-xxhdpi/ic_logo.png
  app/src/main/res/mipmap-xxhdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_logo_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo_round.png
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/ProjectProperties.kt
  gradle.properties
Labels: BUG 🐛
